#!/bin/env python3

# Partially implements the distdir rule generated by Automake, but the list
# of files have to be piped to stdin.

# This implementation is needed because some submodules (MAME) have way
# more files than what sh accepts as number of arguments.

from os.path import dirname, isdir, isfile
from subprocess import call
from sys import argv, stdin
import fileinput

submodule_dir = argv[1]
srcdir = argv[2]
distdir = argv[3]

while True:
    line = stdin.readline().strip('\n')
    if not line:
        break
    if submodule_dir is '.':
        f = line
    else:
        f = submodule_dir + '/' + line

    if isdir(f):
        if not isdir(distdir + '/' + f):
            call(['mkdir', '-p', distdir + '/' + f])

    if isfile(f):
        parent = dirname(distdir + '/' + f)
        if not isdir(parent):
            call(['mkdir', '-p', parent])

    if isfile(f) or isdir(f):
        d = '.'
    else:
        d = srcdir

    if not isdir(d + '/' + f):
        isfile(distdir + '/' + f) or \
        call(['cp', '-p', d + '/' + f, distdir + '/' + f]) == 0 or \
        exit(1)
